language: csharp
solution: PicrossClone.sln
script:
    - xbuild /p:Configuration=Release PicrossClone.sln
    - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./UnitTests/bin/Release/UnitTests.dll
